sudo: required
dist: trusty
language: bash
services:
- docker
before_install:
- sudo rm -f /usr/local/bin/docker-compose
- curl -L https://github.com/docker/compose/releases/download/1.7.1/docker-compose-`uname
  -s`-`uname -m` > docker-compose
- chmod +x docker-compose
- sudo mv docker-compose /usr/local/bin
- sudo service docker restart
- docker-compose -v
- docker -v
script:
- sudo service docker restart
- docker-compose config
- sudo ./quickstart.sh peru
deploy:
  provider: releases
  prerelease: true
  skip_cleanup: true
  api_key:
    secure: ljWJOZkEDRHWJ2zDR5XutEZLwKcgHl9GTRaOJuQBeyYUjlKgbkPxlSh3aeXW1DLPJld91LXgNkDAIcn0syUg7ZaOoD2XJ+G4FV/pOA3/fKHoW4+2LVc921GFOXcWF+Mm9uR1M4rhUH3zhOyCzDdSPUuLW7ZQdIOnnvIiVkYU0NPFDoPzK9/Z6HJvFyegn0NPzpsWVMGyeFf8zgScPoVuTBzpBigHN5wY/b+8UE0Sdajp3L/ycqwuw3cC+Ie4K/+wOA1vSp0amhWKHe1elr2dipvyk8jYEial6QA3qIgfWzQX1JYv4CXkDY7Xr1R/UX3yRxlAu7Id+55HE2OmlH9XGGZZAao3lcesQRnOLjWz+zvooMaTKkdj1GC7dmwt1I1++c7+8LZp2VlKebZYa06+bTiEtxyC7KICSXAtAU6j+6XE6qfRk7usHNGK0Szl5e4ixxzT2YzwPPfdjkOOMtMTs2NgFcNDxx/T6rOP2WnUjP8q0wjTmlLzO/jJ3gEeg6YixM+vj8a1t8MI3yB2KzUJJBa7R3lNTPjgUxB3/H1sF14KFksLeUIxoLlXsHa1Ct83yGuqYBref0Gj4eL9ferZZKLCZWcjBxUblLNVLIpGrnGZUG31eatOrslfWQ5YzBATalIU+n64Wk8G+v2fsb7rKYE8iqAxJW6LkQCeCQil9FA=
  file: data/tiles.mbtiles
  on:
    repo: digidem/mapeo-openmaptiles
